name: BradOS
options:
  bundleIdPrefix: com.bradcarter
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: BradOS/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_TEAM: ""

targets:
  BradOS:
    type: application
    platform: iOS
    sources:
      - path: BradOS
        excludes:
          - "*.xcassets"
      - path: BradOS/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bradcarter.brad-os
        PRODUCT_NAME: "Brad OS"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: BradOS/Info.plist
    info:
      path: BradOS/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchBackground
        UIUserInterfaceStyle: Dark
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSUserNotificationsUsageDescription: BradOS uses notifications to alert you when rest timers complete during workouts.

schemes:
  BradOS:
    build:
      targets:
        BradOS: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
