name: BradOS
options:
  bundleIdPrefix: com.bradcarter
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: top

packages:
  BradOSCore:
    path: BradOSCore
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 11.0.0

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: BradOS/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_TEAM: 6Q7R3U43ZD
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

targets:
  BradOS:
    type: application
    platform: iOS
    sources:
      - path: BradOS
        excludes:
          - "*.xcassets"
          - "Resources/Audio"
          - "GoogleService-Info.plist"
      - path: BradOS/Assets.xcassets
      - path: BradOS/Resources/Audio
        type: folder
        buildPhase: resources
      - path: BradOS/GoogleService-Info.plist
        buildPhase: resources
    dependencies:
      - package: BradOSCore
      - package: Firebase
        product: FirebaseAppCheck
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bradcarter.brad-os
        PRODUCT_NAME: "Brad OS"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: BradOS/Info.plist
    info:
      path: BradOS/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchBackground
        UIUserInterfaceStyle: Dark
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIBackgroundModes:
          - audio
        LSApplicationQueriesSchemes:
          - spotify
        NSUserNotificationsUsageDescription: BradOS uses notifications to alert you when rest timers complete during workouts.

schemes:
  BradOS:
    build:
      targets:
        BradOS: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
